<?php
namespace Page\MuzzaWeb;

class GenresAndSubgenres
{
    // include url of current page

    public static $alternativeGenreCrumbs = '<a class="genre-crumbs" data-href="#station/alternative" href="">Alternative</a>';
    public static $alternativeGenre = '#tab-1';
        public static $adultAlternative = '//*[@id="mCSB_1_container"]/ul/li[1]/a';
        public static $adultAlternativeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/adult-alternative"> / Adult Alternative</span>';
        public static $britpop = '//*[@id="mCSB_1_container"]/ul/li[2]/a';
        public static $britpopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/britpop"> / Britpop</span>';
        public static $classicAlternative = '//*[@id="mCSB_1_container"]/ul/li[3]/a';
        public static $classicAlternativeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/classic-alternative"> / Classic Alternative</span>';
        public static $college = '//*[@id="mCSB_1_container"]/ul/li[4]/a';
        public static $collegeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/college"> / College</span>';
        public static $dancepunk = '//*[@id="mCSB_1_container"]/ul/li[5]/a';
        public static $dancepunkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/dancepunk"> / Dancepunk</span>';
        public static $dreamPop = '//*[@id="mCSB_1_container"]/ul/li[6]/a';
        public static $dreamPopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/dream-pop"> / Dream Pop</span>';
        public static $emo = '//*[@id="mCSB_1_container"]/ul/li[7]/a';
        public static $emoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/emo"> / Emo</span>';
        public static $goth = '//*[@id="mCSB_1_container"]/ul/li[8]/a';
        public static $gothCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/goth"> / Goth</span>';
        public static $grunge = '//*[@id="mCSB_1_container"]/ul/li[9]/a';
        public static $grungeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/grunge"> / Grunge</span>';
        public static $hardcore = '//*[@id="mCSB_1_container"]/ul/li[10]/a';
        public static $hardcoreCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/hardcore"> / Hardcore</span>';
        public static $indiePop = '//*[@id="mCSB_1_container"]/ul/li[11]/a';
        public static $indiePopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/indie-pop"> / Indie Pop</span>';
        public static $indieRock = '//*[@id="mCSB_1_container"]/ul/li[12]/a';
        public static $indieRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/indie-rock"> / Indie Rock</span>';
        public static $industrial = '//*[@id="mCSB_1_container"]/ul/li[13]/a';
        public static $industrialCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/industrial"> / Industrial</span>';
        public static $lofi = '//*[@id="mCSB_1_container"]/ul/li[14]/a';
        public static $lofiCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/lofi"> / LoFi</span>';
        public static $modernRock = '//*[@id="mCSB_1_container"]/ul/li[15]/a';
        public static $modernRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/modern-rock"> / Modern Rock</span>';
        public static $newWave = '//*[@id="mCSB_1_container"]/ul/li[16]/a';
        public static $newWaveCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/new-wave"> / New Wave</span>';
        public static $noisePop = '//*[@id="mCSB_1_container"]/ul/li[17]/a';
        public static $noisePopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/noise-pop"> / Noise Pop</span>';
        public static $postPunk = '//*[@id="mCSB_1_container"]/ul/li[18]/a';
        public static $postPunkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/post-punk"> / Post Punk</span>';
        public static $powerPop = '//*[@id="mCSB_1_container"]/ul/li[19]/a';
        public static $powerPopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/power-pop"> / Power Pop</span>';
        public static $punk = '//*[@id="mCSB_1_container"]/ul/li[20]/a';
        public static $punkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/punk"> / Punk</span>';
        public static $skaRock = '//*[@id="mCSB_1_container"]/ul/li[21]/a';
        public static $skaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/ska"> / Ska</span>';
        public static $xtremeRock = '//*[@id="mCSB_1_container"]/ul/li[22]/a';
        public static $xtremeRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/alternative/xtreme"> / Xtreme</span>';

    public static $bluesGenre = '#tab-2';
    public static $bluesGenreCrumbs = '<a class="genre-crumbs" data-href="#station/blues" href="">Blues</a>';
        public static $acousticBlues = '//*[@id="mCSB_2_container"]/ul/li[1]/a';
        public static $acousticBluesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/blues/acoustic-blues"> / Acoustic Blues</span>';
        public static $cajunAndZydeco = '//*[@id="mCSB_2_container"]/ul/li[2]/a';
        public static $cajunAndZydecoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/blues/cajun-and-zydeco"> / Cajun and Zydeco</span>';
        public static $chicagoBlues = '//*[@id="mCSB_2_container"]/ul/li[3]/a';
        public static $chicagoBluesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/blues/chicago-blues"> / Chicago Blues</span>';
        public static $contemporaryBlues = '//*[@id="mCSB_2_container"]/ul/li[4]/a';
        public static $contemporaryBluesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/blues/contemporary-blues"> / Contemporary Blues</span>';
        public static $countryBlues = '//*[@id="mCSB_2_container"]/ul/li[5]/a';
        public static $countryBluesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/blues/country-blues"> / Country Blues</span>';
        public static $deltaBlues = '//*[@id="mCSB_2_container"]/ul/li[6]/a';
        public static $deltaBluesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/blues/delta-blues"> / Delta Blues</span>';
        public static $electricBlues = '//*[@id="mCSB_2_container"]/ul/li[7]/a';
        public static $electricBluesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/blues/electric-blues"> / Electric Blues</span>';

    public static $classicalGenre = '#tab-3';
    public static $classicalGenreCrumbs = '<a class="genre-crumbs" data-href="#station/classical" href="">Classical</a>';
        public static $baroque = '//*[@id="mCSB_3_container"]/ul/li[1]/a';
        public static $baroqueCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/baroque"> / Baroque</span>';
        public static $chamber = '//*[@id="mCSB_3_container"]/ul/li[2]/a';
        public static $chamberCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/chamber"> / Chamber</span>';
        public static $choral = '//*[@id="mCSB_3_container"]/ul/li[3]/a';
        public static $choralCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/choral"> / Choral</span>';
        public static $classicalPeriod = '//*[@id="mCSB_3_container"]/ul/li[4]/a';
        public static $classicalPeriodCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/classical-period"> / Classical Period</span>';
        public static $earlyClassical = '//*[@id="mCSB_3_container"]/ul/li[5]/a';
        public static $earlyClassicalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/early-classical"> / Early Classical</span>';
        public static $impressionist = '//*[@id="mCSB_3_container"]/ul/li[6]/a';
        public static $impressionistCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/impressionist"> / Impressionist</span>';
        public static $modern = '//*[@id="mCSB_3_container"]/ul/li[7]/a';
        public static $modernCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/modern"> / Modern</span>';
        public static $opera = '//*[@id="mCSB_3_container"]/ul/li[8]/a';
        public static $operaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/opera"> / Opera</span>';
        public static $piano = '//*[@id="mCSB_3_container"]/ul/li[9]/a';
        public static $pianoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/piano"> / Piano</span>';
        public static $romantic = '//*[@id="mCSB_3_container"]/ul/li[10]/a';
        public static $romanticCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/romantic"> / Romantic</span>';
        public static $symphony = '//*[@id="mCSB_3_container"]/ul/li[11]/a';
        public static $symphonyCrumbs = '<span class="sub-genre-crumbs" data-href="#station/classical/symphony"> / Symphony</span>';




    public static $countryGenre = '#tab-4';
    public static $countryGenreCrumbs = '<a class="genre-crumbs" data-href="#station/country" href="">Country</a>';
        public static $altCountry = '//*[@id="mCSB_4_container"]/ul/li[1]/a';
        public static $altCountryCrumbs = '<span class="sub-genre-crumbs" data-href="#station/country/alt-country"> / Alt Country</span>';
        public static $americana = '//*[@id="mCSB_4_container"]/ul/li[2]/a';
        public static $americanaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/country/americana"> / Americana</span>';
        public static $bluegrass = '//*[@id="mCSB_4_container"]/ul/li[3]/a';
        public static $bluegrassCrumbs = '<span class="sub-genre-crumbs" data-href="#station/country/bluegrass"> / Bluegrass</span>';
        public static $classicCountry = '//*[@id="mCSB_4_container"]/ul/li[4]/a';
        public static $classicCountryCrumbs = '<span class="sub-genre-crumbs" data-href="#station/country/classic-country"> / Classic Country</span>';
        public static $contemporaryBluegrass = '//*[@id="mCSB_4_container"]/ul/li[5]/a';
        public static $contemporaryBluegrassCrumbs = '<span class="sub-genre-crumbs" data-href="#station/country/contemporary-bluegrass"> / Contemporary Bluegrass</span>';
        public static $contemporaryCountry = '//*[@id="mCSB_4_container"]/ul/li[6]/a';
        public static $contemporaryCountryCrumbs = '<span class="sub-genre-crumbs" data-href="#station/country/contemporary-country"> / Contemporary Country</span>';
        public static $honkyTonk = '//*[@id="mCSB_4_container"]/ul/li[7]/a';
        public static $honkyTonkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/country/honky-tonk"> / Honky Tonk</span>';
        public static $hotCountryHits = '//*[@id="mCSB_4_container"]/ul/li[8]/a';
        public static $hotCountryHitsCrumbs = '<span class="sub-genre-crumbs" data-href="#station/country/hot-country-hits"> / Hot Country Hits</span>';
        public static $western = '//*[@id="mCSB_4_container"]/ul/li[9]/a';
        public static $westernCrumbs = '<span class="sub-genre-crumbs" data-href="#station/country/western"> / Western</span>';


    public static $decadesGenre = '#tab-5';
    public static $decadesGenreCrumbs = '<a class="genre-crumbs" data-href="#station/decades" href="">Decades</a>';
        public static $d00s = '//*[@id="mCSB_5_container"]/ul/li[1]/a';
        public static $d00sCrumbs = '<span class="sub-genre-crumbs" data-href="#station/decades/00s"> / 00s</span>';
        public static $d30s = '//*[@id="mCSB_5_container"]/ul/li[2]/a';
        public static $d30sCrumbs = '<span class="sub-genre-crumbs" data-href="#station/decades/30s"> / 30s</span>';
        public static $d40s = '//*[@id="mCSB_5_container"]/ul/li[3]/a';
        public static $d40sCrumbs = '<span class="sub-genre-crumbs" data-href="#station/decades/40s"> / 40s</span>';
        public static $d50s = '//*[@id="mCSB_5_container"]/ul/li[4]/a';
        public static $d50sCrumbs = '<span class="sub-genre-crumbs" data-href="#station/decades/50s"> / 50s</span>';
        public static $d60s = '//*[@id="mCSB_5_container"]/ul/li[5]/a';
        public static $d60sCrumbs = '<span class="sub-genre-crumbs" data-href="#station/decades/60s"> / 60s</span>';
        public static $d70s = '//*[@id="mCSB_5_container"]/ul/li[6]/a';
        public static $d70sCrumbs = '<span class="sub-genre-crumbs" data-href="#station/decades/70s"> / 70s</span>';
        public static $d80s = '//*[@id="mCSB_5_container"]/ul/li[7]/a';
        public static $d80sCrumbs = '<span class="sub-genre-crumbs" data-href="#station/decades/80s"> / 80s</span>';
        public static $d90s = '//*[@id="mCSB_5_container"]/ul/li[8]/a';
        public static $d90sCrumbs = '<span class="sub-genre-crumbs" data-href="#station/decades/90s"> / 90s</span>';


    public static $easyListeningGenre = '#tab-6';
    public static $easyListeningGenreCrumbs = '<a class="genre-crumbs" data-href="#station/easy-listening" href="">Easy Listening</a>';
        public static $exotica = '//*[@id="mCSB_6_container"]/ul/li[1]/a';
        public static $exoticaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/easy-listening/exotica"> / Exotica</span>';
        public static $lightRock = '//*[@id="mCSB_6_container"]/ul/li[2]/a';
        public static $lightRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/easy-listening/light-rock"> / Light Rock</span>';
        public static $lounge = '//*[@id="mCSB_6_container"]/ul/li[3]/a';
        public static $loungeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/easy-listening/lounge"> / Lounge</span>';
        public static $orchestralPop = '//*[@id="mCSB_6_container"]/ul/li[4]/a';
        public static $orchestralPopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/easy-listening/orchestral-pop"> / Orchestral Pop</span>';
        public static $polka = '//*[@id="mCSB_6_container"]/ul/li[5]/a';
        public static $polkaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/easy-listening/polka"> / Polka</span>';
        public static $spaceAgePop = '//*[@id="mCSB_6_container"]/ul/li[6]/a';
        public static $spaceAgePopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/easy-listening/space-age-pop"> / Space Age Pop</span>';


    public static $electronicGenre = '#tab-7';
    public static $electronicGenreCrumbs = '<a class="genre-crumbs" data-href="#station/electronic" href="">Electronic</a>';
        public static $acidHouse = '//*[@id="mCSB_7_container"]/ul/li[1]/a';
        public static $acidHouseCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/acid-house"> / Acid House</span>';
        public static $ambient = '//*[@id="mCSB_7_container"]/ul/li[2]/a';
        public static $ambientCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/ambient"> / Ambient</span>';
        public static $bigBeat = '//*[@id="mCSB_7_container"]/ul/li[3]/a';
        public static $bigBeatCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/big-beat"> / Big Beat</span>';
        public static $breakBeat = '//*[@id="mCSB_7_container"]/ul/li[4]/a';
        public static $breakBeatCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/breakbeat"> / Breakbeat</span>';
        public static $dance = '//*[@id="mCSB_7_container"]/ul/li[5]/a';
        public static $danceCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/dance"> / Dance</span>';
        public static $demo = '//*[@id="mCSB_7_container"]/ul/li[6]/a';
        public static $demoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/demo"> / Demo</span>';
        public static $disco = '//*[@id="mCSB_7_container"]/ul/li[7]/a';
        public static $discoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/disco"> / Disco</span>';
        public static $dowmTempo = '//*[@id="mCSB_7_container"]/ul/li[8]/a';
        public static $downTempoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/downtempo"> / Downtempo</span>';
        public static $drumNbass = '//*[@id="mCSB_7_container"]/ul/li[9]/a';
        public static $drumNbassCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/drum-and-bass"> / Drum and Bass</span>';
        public static $dubstep = '//*[@id="mCSB_7_container"]/ul/li[10]/a';
        public static $dubstapCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/dubstep"> / Dubstep</span>';
        public static $electro = '//*[@id="mCSB_7_container"]/ul/li[11]/a';
        public static $electroCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/electro"> / Electro</span>';
        public static $garage = '//*[@id="mCSB_7_container"]/ul/li[12]/a';
        public static $garageCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/garage"> / Garage</span>';
        public static $hardHouse = '//*[@id="mCSB_7_container"]/ul/li[13]/a';
        public static $hardHouseCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/hard-house"> / Hard House</span>';
        public static $house = '//*[@id="mCSB_7_container"]/ul/li[14]/a';
        public static $houseCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/house"> / House</span>';
        public static $idm = '//*[@id="mCSB_7_container"]/ul/li[15]/a';
        public static $idmCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/idm"> / IDM</span>';
        public static $jungle = '//*[@id="mCSB_7_container"]/ul/li[16]/a';
        public static $jungleCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/jungle"> / Jungle</span>';
        public static $progressive = '//*[@id="mCSB_7_container"]/ul/li[17]/a';
        public static $progressiveCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/progressive"> / Progressive</span>';
        public static $techno = '//*[@id="mCSB_7_container"]/ul/li[18]/a';
        public static $technoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/techno"> / Techno</span>';
        public static $trance = '//*[@id="mCSB_7_container"]/ul/li[19]/a';
        public static $tranceCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/trance"> / Trance</span>';
        public static $tribal = '//*[@id="mCSB_7_container"]/ul/li[20]/a';
        public static $tribalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/tribal"> / Tribal</span>';
        public static $tripHop = '//*[@id="mCSB_7_container"]/ul/li[21]/a';
        public static $tripHopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/electronic/trip-hop"> / Trip Hop</span>';


    public static $folkGenre = '#tab-8';
    public static $foldGenreCrumbs = '<a class="genre-crumbs" data-href="#station/folk" href="">Folk</a>';
        public static $alternativeFolk = '//*[@id="mCSB_8_container"]/ul/li[1]/a';
        public static $alternativeFolkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/folk/alternative-folk"> / Alternative Folk</span>';
        public static $contemporaryFolk = '//*[@id="mCSB_8_container"]/ul/li[1]/a';
        public static $contemporaryFolkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/folk/contemporary-folk"> / Contemporary Folk</span>';
        public static $folkRock = '//*[@id="mCSB_8_container"]/ul/li[1]/a';
        public static $folkRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/folk/folk-rock"> / Folk Rock</span>';
        public static $newAcoustic = '//*[@id="mCSB_8_container"]/ul/li[1]/a';
        public static $newAcousticCrumbs = '<span class="sub-genre-crumbs" data-href="#station/folk/new-acoustic"> / New Acoustic</span>';
        public static $oldTime = '//*[@id="mCSB_8_container"]/ul/li[1]/a';
        public static $oldTimeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/folk/old-time"> / Old Time</span>';
        public static $traditionalFolk = '//*[@id="mCSB_8_container"]/ul/li[1]/a';
        public static $traditionalFolkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/folk/traditional-folk"> / Traditional Folk</span>';
        public static $worldFolk = '//*[@id="mCSB_8_container"]/ul/li[1]/a';
        public static $worldFolkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/folk/world-folk"> / World Folk</span>';


    public static $inspirationalGenre = '#tab-9';
    public static $inspirationalGenreCrumbs = '<a class="genre-crumbs" data-href="#station/inspirational" href="">Inspirational</a>';
        public static $christian = '//*[@id="mCSB_9_container"]/ul/li[1]/a';
        public static $christianCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/christian"> / Christian</span>';
        public static $christianMetal = '//*[@id="mCSB_9_container"]/ul/li[2]/a';
        public static $christianMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/christian-metal"> / Christian Metal</span>';
        public static $christianRap = '//*[@id="mCSB_9_container"]/ul/li[3]/a';
        public static $christianRapCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/christian-rap"> / Christian Rap</span>';
        public static $christianRock = '//*[@id="mCSB_9_container"]/ul/li[4]/a';
        public static $christianRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/christian-rock"> / Christian Rock</span>';
        public static $classicChristian = '//*[@id="mCSB_9_container"]/ul/li[5]/a';
        public static $classicChristianCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/classic-christian"> / Classic Christian</span>';
        public static $contemporaryGospel = '//*[@id="mCSB_9_container"]/ul/li[6]/a';
        public static $contemporaryGospelCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/contemporary-gospel"> / Contemporary Gospel</span>';
        public static $gospel = '//*[@id="mCSB_9_container"]/ul/li[7]/a';
        public static $gospelCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/gospel"> / Gospel</span>';
        public static $praiseAndWorship = '//*[@id="mCSB_9_container"]/ul/li[8]/a';
        public static $praiseAndWorshipCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/praise-and-worship"> / Praise and Worship</span>';
        public static $sermonsAndServices = '//*[@id="mCSB_9_container"]/ul/li[9]/a';
        public static $sermonsAndServicesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/sermons-and-services"> / Sermons and Services</span>';
        public static $southernGospel = '//*[@id="mCSB_9_container"]/ul/li[10]/a';
        public static $southernGospelCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/southern-gospel"> / Southern Gospel</span>';
        public static $traditionalGospel = '//*[@id="mCSB_9_container"]/ul/li[11]/a';
        public static $traditionalGospelCrumbs = '<span class="sub-genre-crumbs" data-href="#station/inspirational/traditional-gospel"> / Traditional Gospel</span>';


    public static $internationalGenre = '#tab-10';
    public static $internationalCrumbs = '<a class="genre-crumbs" data-href="#station/international" href="">International</a>';
        public static $african = '//*[@id="mCSB_10_container"]/ul/li[1]/a';
        public static $africanCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/african"> / African</span>';
        public static $afrikaans = '//*[@id="mCSB_10_container"]/ul/li[2]/a';
        public static $afrikaansCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/afrikaans"> / Afrikaans</span>';
        public static $arabic = '//*[@id="mCSB_10_container"]/ul/li[3]/a';
        public static $arabicCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/arabic"> / Arabic</span>';
        public static $asian = '//*[@id="mCSB_10_container"]/ul/li[4]/a';
        public static $asianCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/asian"> / Asian</span>';
        public static $bollywood = '//*[@id="mCSB_10_container"]/ul/li[5]/a';
        public static $bollywoodCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/bollywood"> / Bollywood</span>';
        public static $brazilian = '//*[@id="mCSB_10_container"]/ul/li[6]/a';
        public static $brazilianCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/brazilian"> / Brazilian</span>';
        public static $caribbean = '//*[@id="mCSB_10_container"]/ul/li[7]/a';
        public static $caribbeanCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/caribbean"> / Caribbean</span>';
        public static $celtic = '//*[@id="mCSB_10_container"]/ul/li[8]/a';
        public static $celticCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/celtic"> / Celtic</span>';
        public static $chinese = '//*[@id="mCSB_10_container"]/ul/li[9]/a';
        public static $chineseCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/chinese"> / Chinese</span>';
        public static $creole = '//*[@id="mCSB_10_container"]/ul/li[10]/a';
        public static $creoleCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/creole"> / Creole</span>';
        public static $european = '//*[@id="mCSB_10_container"]/ul/li[11]/a';
        public static $europeanCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/european"> / European</span>';
        public static $filipino = '//*[@id="mCSB_10_container"]/ul/li[12]/a';
        public static $filipinoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/filipino"> / Filipino</span>';
        public static $french = '//*[@id="mCSB_10_container"]/ul/li[13]/a';
        public static $frenchCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/french"> / French</span>';
        public static $german = '//*[@id="mCSB_10_container"]/ul/li[14]/a';
        public static $germanCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/german"> / German</span>';
        public static $greek = '//*[@id="mCSB_10_container"]/ul/li[15]/a';
        public static $greekCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/greek"> / Greek</span>';
        public static $hawaiinAndPacific = '//*[@id="mCSB_10_container"]/ul/li[16]/a';
        public static $hawaiinAndPacificCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/hawaiian-and-pacific"> / Hawaiian and Pacific</span>';
        public static $hebrew = '//*[@id="mCSB_10_container"]/ul/li[17]/a';
        public static $hebrewCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/hebrew"> / Hebrew</span>';
        public static $hindi = '//*[@id="mCSB_10_container"]/ul/li[18]/a';
        public static $hindiCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/hindi"> / Hindi</span>';
        public static $indian = '//*[@id="mCSB_10_container"]/ul/li[19]/a';
        public static $indianCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/indian"> / Indian</span>';
        public static $islamic = '//*[@id="mCSB_10_container"]/ul/li[20]/a';
        public static $islamicCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/islamic"> / Islamic</span>';
        public static $japanese = '//*[@id="mCSB_10_container"]/ul/li[21]/a';
        public static $japaneseCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/japanese"> / Japanese</span>';
        public static $klezmer = '//*[@id="mCSB_10_container"]/ul/li[22]/a';
        public static $klezmerCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/klezmer"> / Klezmer</span>';
        public static $korean = '//*[@id="mCSB_10_container"]/ul/li[23]/a';
        public static $koreanCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/korean"> / Korean</span>';
        public static $mediterranean = '//*[@id="mCSB_10_container"]/ul/li[24]/a';
        public static $mediterraneanCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/mediterranean"> / Mediterranean</span>';
        public static $middleEastern = '//*[@id="mCSB_10_container"]/ul/li[25]/a';
        public static $middleEasternCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/middle-eastern"> / Middle Eastern</span>';
        public static $northAmerica = '//*[@id="mCSB_10_container"]/ul/li[26]/a';
        public static $northAmericaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/north-american"> / North American</span>';
        public static $russian = '//*[@id="mCSB_10_container"]/ul/li[27]/a';
        public static $russianCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/russian"> / Russian</span>';
        public static $soca = '//*[@id="mCSB_10_container"]/ul/li[28]/a';
        public static $socaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/soca"> / Soca</span>';
        public static $southAmerican = '//*[@id="mCSB_10_container"]/ul/li[29]/a';
        public static $southAmericanCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/south-american"> / South American</span>';
        public static $tamil = '//*[@id="mCSB_10_container"]/ul/li[30]/a';
        public static $tamilCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/tamil"> / Tamil</span>';
        public static $turkish = '//*[@id="mCSB_10_container"]/ul/li[31]/a';
        public static $turkishCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/turkish"> / Turkish</span>';
        public static $worldBeat = '//*[@id="mCSB_10_container"]/ul/li[32]/a';
        public static $worldBeatCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/worldbeat"> / Worldbeat</span>';
        public static $zouk = '//*[@id="mCSB_10_container"]/ul/li[33]/a';
        public static $zoukCrumbs = '<span class="sub-genre-crumbs" data-href="#station/international/zouk"> / Zouk</span>';


    public static $jazzGenre = '#tab-11';
    public static $jazzGenreCrumbs = '<a class="genre-crumbs" data-href="#station/jazz" href="">Jazz</a>';
        public static $acidJazz = '//*[@id="mCSB_11_container"]/ul/li[1]/a';
        public static $acidJazzCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/acid-jazz"> / Acid Jazz</span>';
        public static $avantGarde = '//*[@id="mCSB_11_container"]/ul/li[2]/a';
        public static $avantGardeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/avant-garde"> / Avant Garde</span>';
        public static $bigBand = '//*[@id="mCSB_11_container"]/ul/li[3]/a';
        public static $bigBandCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/big-band"> / Big Band</span>';
        public static $bop = '//*[@id="mCSB_11_container"]/ul/li[4]/a';
        public static $bopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/bop"> / Bop</span>';
        public static $classicJazz = '//*[@id="mCSB_11_container"]/ul/li[5]/a';
        public static $classicJazzCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/classic-jazz"> / Classic Jazz</span>';
        public static $coolJazz = '//*[@id="mCSB_11_container"]/ul/li[6]/a';
        public static $coolJazzCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/cool-jazz"> / Cool Jazz</span>';
        public static $fusion = '//*[@id="mCSB_11_container"]/ul/li[7]/a';
        public static $fusionCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/fusion"> / Fusion</span>';
        public static $hardBop = '//*[@id="mCSB_11_container"]/ul/li[8]/a';
        public static $hardBopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/hard-bop"> / Hard Bop</span>';
        public static $latinJazz = '//*[@id="mCSB_11_container"]/ul/li[9]/a';
        public static $latinJazzCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/latin-jazz"> / Latin Jazz</span>';
        public static $smoothJazz = '//*[@id="mCSB_11_container"]/ul/li[10]/a';
        public static $smoothJazzCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/smooth-jazz"> / Smooth Jazz</span>';
        public static $swing = '//*[@id="mCSB_11_container"]/ul/li[11]/a';
        public static $swingCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/swing"> / Swing</span>';
        public static $vocalJazz = '//*[@id="mCSB_11_container"]/ul/li[12]/a';
        public static $vocalJazzCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/vocal-jazz"> / Vocal Jazz</span>';
        public static $worldFusion = '//*[@id="mCSB_11_container"]/ul/li[13]/a';
        public static $worldFusionCrumbs = '<span class="sub-genre-crumbs" data-href="#station/jazz/world-fusion"> / World Fusion</span>';






    public static $latinGenre = '#tab-12';
    public static $latinGenreCrumbs = '<a class="genre-crumbs" data-href="#station/latin" href="">Latin</a>';
        public static $bacata = '//*[@id="mCSB_12_container"]/ul/li[1]/a';
        public static $bacataCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/bachata"> / Bachata</span>';
        public static $banda = '//*[@id="mCSB_12_container"]/ul/li[2]/a';
        public static $bandaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/banda"> / Banda</span>';
        public static $bossaNova = '//*[@id="mCSB_12_container"]/ul/li[3]/a';
        public static $bossaNovaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/bossa-nova"> / Bossa Nova</span>';
        public static $cumbia = '//*[@id="mCSB_12_container"]/ul/li[4]/a';
        public static $cumbiaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/cumbia"> / Cumbia</span>';
        public static $flamenco = '//*[@id="mCSB_12_container"]/ul/li[5]/a';
        public static $flamencoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/flamenco"> / Flamenco</span>';
        public static $latinDance = '//*[@id="mCSB_12_container"]/ul/li[6]/a';
        public static $latinDanceCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/latin-dance"> / Latin Dance</span>';
        public static $latinPop = '//*[@id="mCSB_12_container"]/ul/li[7]/a';
        public static $latinPopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/latin-pop"> / Latin Pop</span>';
        public static $latinRapHipHop = '//*[@id="mCSB_12_container"]/ul/li[8]/a';
        public static $latinRapHipHopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/latin-rap-and-hip-hop"> / Latin Rap and Hip Hop</span>';
        public static $latinRock = '//*[@id="mCSB_12_container"]/ul/li[9]/a';
        public static $latinRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/latin-rock"> / Latin Rock</span>';
        public static $mariachi = '//*[@id="mCSB_12_container"]/ul/li[10]/a';
        public static $mariachiCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/mariachi"> / Mariachi</span>';
        public static $merengue = '//*[@id="mCSB_12_container"]/ul/li[11]/a';
        public static $merengueCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/merengue"> / Merengue</span>';
        public static $ranchera = '//*[@id="mCSB_12_container"]/ul/li[12]/a';
        public static $rancheraCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/ranchera"> / Ranchera</span>';
        public static $reggaeton = '//*[@id="mCSB_12_container"]/ul/li[13]/a';
        public static $reggaetonCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/reggaeton"> / Reggaeton</span>';
        public static $regionalMexican = '//*[@id="mCSB_12_container"]/ul/li[14]/a';
        public static $regionalMexicanCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/regional-mexican"> / Regional Mexican</span>';
        public static $salsa = '//*[@id="mCSB_12_container"]/ul/li[15]/a';
        public static $salsaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/salsa"> / Salsa</span>';
        public static $samba = '//*[@id="mCSB_12_container"]/ul/li[16]/a';
        public static $sambaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/samba"> / Samba</span>';
        public static $tango = '//*[@id="mCSB_12_container"]/ul/li[17]/a';
        public static $tangoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/tango"> / Tango</span>';
        public static $tejano = '//*[@id="mCSB_12_container"]/ul/li[18]/a';
        public static $tejanoCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/tejano"> / Tejano</span>';
        public static $tropicalia = '//*[@id="mCSB_12_container"]/ul/li[19]/a';
        public static $tropicaliaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/latin/tropicalia"> / Tropicalia</span>';


    public static $metalGenre = '#tab-13';
    public static $metalgenreCrumbs = '<a class="genre-crumbs" data-href="#station/metal" href="">Metal</a>';
        public static $blackMetal = '//*[@id="mCSB_13_container"]/ul/li[2]/a';
        public static $blackMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/black-metal"> / Black Metal</span>';
        public static $classicMetal = '//*[@id="mCSB_13_container"]/ul/li[3]/a';
        public static $classicMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/classic-metal"> / Classic Metal</span>';
        public static $deathMetal = '//*[@id="mCSB_13_container"]/ul/li[4]/a';
        public static $deathMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/death-metal"> / Death Metal</span>';
        public static $extremeMetal = '//*[@id="mCSB_13_container"]/ul/li[5]/a';
        public static $extremeMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/extreme-metal"> / Extreme Metal</span>';
        public static $grindcore = '//*[@id="mCSB_13_container"]/ul/li[6]/a';
        public static $grindcoreCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/grindcore"> / Grindcore</span>';
        public static $hairMetal = '//*[@id="mCSB_13_container"]/ul/li[7]/a';
        public static $hairMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/hair-metal"> / Hair Metal</span>';
        public static $heavyMetal = '//*[@id="mCSB_13_container"]/ul/li[8]/a';
        public static $heavyMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/heavy-metal"> / Heavy Metal</span>';
        public static $metalcore = '//*[@id="mCSB_13_container"]/ul/li[9]/a';
        public static $metalcoreCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/metalcore"> / Metalcore</span>';
        public static $powerMetal = '//*[@id="mCSB_13_container"]/ul/li[10]/a';
        public static $powerMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/power-metal"> / Power Metal</span>';
        public static $progressiveMetal = '//*[@id="mCSB_13_container"]/ul/li[11]/a';
        public static $progressiveMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/progressive-metal"> / Progressive Metal</span>';
        public static $rapMetal = '//*[@id="mCSB_13_container"]/ul/li[12]/a';
        public static $rapMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/rap-metal"> / Rap Metal</span>';
        public static $thrashMetal = '//*[@id="mCSB_13_container"]/ul/li[13]/a';
        public static $thrashMetalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/metal/thrash-metal"> / Thrash Metal</span>';


    public static $miscGenre = '#tab-14';
    public static $miscGenreCrumbs = '<a class="genre-crumbs" data-href="#station/misc" href="">Misc</a>';

    public static $newAgeGenre = '#tab-15';
    public static $newAgeGenreCrumbs = '<a class="genre-crumbs" data-href="#station/new-age" href="">New Age</a>';
        public static $environmental = '//*[@id="mCSB_15_container"]/ul/li[1]/a';
        public static $environmentalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/new-age/environmental"> / Environmental</span>';
        public static $ethnicFusion = '//*[@id="mCSB_15_container"]/ul/li[2]/a';
        public static $ethnicFusionCrumbs = '<span class="sub-genre-crumbs" data-href="#station/new-age/ethnic-fusion"> / Ethnic Fusion</span>';
        public static $healing = '//*[@id="mCSB_15_container"]/ul/li[3]/a';
        public static $healingCrumbs = '<span class="sub-genre-crumbs" data-href="#station/new-age/healing"> / Healing</span>';
        public static $meditation = '//*[@id="mCSB_15_container"]/ul/li[4]/a';
        public static $meditationCrumbs = '<span class="sub-genre-crumbs" data-href="#station/new-age/meditation"> / Meditation</span>';
        public static $spiritual = '//*[@id="mCSB_15_container"]/ul/li[5]/a';
        public static $spiritualCrumbs = '<span class="sub-genre-crumbs" data-href="#station/new-age/spiritual"> / Spiritual</span>';


    public static $popGenre = '#tab-16';
    public static $popGenreCrumbs = '<a class="genre-crumbs" data-href="#station/pop" href="">Pop</a>';
        public static $adultContemporary = '//*[@id="mCSB_16_container"]/ul/li[1]/a';
        public static $adultContemporaryCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/adult-contemporary"> / Adult Contemporary</span>';
        public static $barbershop = '//*[@id="mCSB_16_container"]/ul/li[2]/a';
        public static $barbershopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/barbershop"> / Barbershop</span>';
        public static $bubblegunPop = '//*[@id="mCSB_16_container"]/ul/li[3]/a';
        public static $bubblegunPopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/bubblegum-pop"> / Bubblegum Pop</span>';
        public static $dancePop = '//*[@id="mCSB_16_container"]/ul/li[4]/a';
        public static $dancePopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/dance-pop"> / Dance Pop</span>';
        public static $idols = '//*[@id="mCSB_16_container"]/ul/li[5]/a';
        public static $idolsCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/idols"> / Idols</span>';
        public static $jpop = '//*[@id="mCSB_16_container"]/ul/li[6]/a';
        public static $jpopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/jpop"> / JPOP</span>';
        public static $kpop = '//*[@id="mCSB_16_container"]/ul/li[7]/a';
        public static $kpopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/kpop"> / KPOP</span>';
        public static $oldies = '//*[@id="mCSB_16_container"]/ul/li[8]/a';
        public static $oldiesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/oldies"> / Oldies</span>';
        public static $softRock = '//*[@id="mCSB_16_container"]/ul/li[9]/a';
        public static $softRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/soft-rock"> / Soft Rock</span>';
        public static $teenPop = '//*[@id="mCSB_16_container"]/ul/li[10]/a';
        public static $teenPopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/teen-pop"> / Teen Pop</span>';
        public static $top40 = '//*[@id="mCSB_16_container"]/ul/li[11]/a';
        public static $top40Crumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/top-40"> / Top 40</span>';
        public static $worldPop = '//*[@id="mCSB_16_container"]/ul/li[12]/a';
        public static $worldPopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/pop/world-pop"> / World Pop</span>';

    public static $publicGenre = '#tab-17';
    public static $publicGenreCrumbs = '<a class="genre-crumbs" data-href="#station/public-radio" href="">Public Radio</a>';
        public static $collage1 = '//*[@id="mCSB_17_container"]/ul/li[1]/a';
        public static $collage1Crumbs = '<span class="sub-genre-crumbs" data-href="#station/public-radio/college-1"> / College</span>';
        public static $news = '//*[@id="mCSB_17_container"]/ul/li[2]/a';
        public static $newsCrumbs = '<span class="sub-genre-crumbs" data-href="#station/public-radio/news"> / News</span>';
        public static $sport = '//*[@id="mCSB_17_container"]/ul/li[3]/a';
        public static $sportCrumbs = '<span class="sub-genre-crumbs" data-href="#station/public-radio/sports"> / Sports</span>';
        public static $talk = '//*[@id="mCSB_17_container"]/ul/li[4]/a';
        public static $talkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/public-radio/talk-1"> / Talk</span>';
        public static $weather = '//*[@id="mCSB_17_container"]/ul/li[5]/a';
        public static $weatherCrumbs = '<span class="sub-genre-crumbs" data-href="#station/public-radio/weather"> / Weather</span>';




    public static $rAndBGenre = '#tab-18';
    public static $rAndBGenreCrumbs = '<a class="genre-crumbs" data-href="#station/rb-and-urban" href="">R&amp;B and Urban</a>';
        public static $classicRB = '//*[@id="mCSB_18_container"]/ul/li[1]/a';
        public static $classicRBCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rb-and-urban/classic-rb"> / Classic R&amp;B</span>';
        public static $contemporaryRB = '//*[@id="mCSB_18_container"]/ul/li[2]/a';
        public static $contemporaryRBCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rb-and-urban/contemporary-rb"> / Contemporary R&amp;B</span>';
        public static $doowoo = '//*[@id="mCSB_18_container"]/ul/li[3]/a';
        public static $doowooCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rb-and-urban/doo-wop"> / Doo Wop</span>';
        public static $funk = '//*[@id="mCSB_18_container"]/ul/li[4]/a';
        public static $funkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rb-and-urban/funk"> / Funk</span>';
        public static $motown = '//*[@id="mCSB_18_container"]/ul/li[5]/a';
        public static $motownCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rb-and-urban/motown"> / Motown</span>';
        public static $neoSoul = '//*[@id="mCSB_18_container"]/ul/li[6]/a';
        public static $neoSoulCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rb-and-urban/neo-soul"> / Neo Soul</span>';
        public static $quietStorm = '//*[@id="mCSB_18_container"]/ul/li[7]/a';
        public static $quietStormCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rb-and-urban/quiet-storm"> / Quiet Storm</span>';
        public static $soul = '//*[@id="mCSB_18_container"]/ul/li[8]/a';
        public static $soulCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rb-and-urban/soul"> / Soul</span>';
        public static $urbanContemporary = '//*[@id="mCSB_18_container"]/ul/li[9]/a';
        public static $urbanContemporaryCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rb-and-urban/urban-contemporary"> / Urban Contemporary</span>';


    public static $rapGenre = '#tab-19';
    public static $rapGenreCrumbs = '<a class="genre-crumbs" data-href="#station/rap" href="">Rap</a>';
        public static $alternativeRap = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $alternativeRapCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/alternative-rap"> / Alternative Rap</span>';
        public static $dirtySouth = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $dirtySouthCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/dirty-south"> / Dirty South</span>';
        public static $eastCoastRap = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $eastCoastRapCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/east-coast-rap"> / East Coast Rap</span>';
        public static $freestyle = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $freestyleCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/freestyle"> / Freestyle</span>';
        public static $gangstaRap = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $gangstaRapCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/gangsta-rap"> / Gangsta Rap</span>';
        public static $hipHop = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $hipHopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/hip-hop"> / Hip Hop</span>';
        public static $mixtapes = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $mixtapesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/mixtapes"> / Mixtapes</span>';
        public static $oldSchool = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $oldSchoolCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/old-school"> / Old School</span>';
        public static $turntablism = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $turntablismCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/turntablism"> / Turntablism</span>';
        public static $undergroundHiphop = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $undergroundHiphopCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/underground-hip-hop"> / Underground Hip Hop</span>';
        public static $westCoastRap = '//*[@id="mCSB_19_container"]/ul/li[1]/a';
        public static $westCoastRapCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rap/west-coast-rap"> / West Coast Rap</span>';


    public static $reggaeGenre = '#tab-20';
    public static $reggaeGenreCrumbs = 'westCoastRap';
        public static $contemporaryReggae = '//*[@id="mCSB_20_container"]/ul/li[1]/a';
        public static $contemporaryReggaeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/reggae/contemporary-reggae"> / Contemporary Reggae</span>';
        public static $dancehall = '//*[@id="mCSB_20_container"]/ul/li[2]/a';
        public static $dancehallCrumbs = '<span class="sub-genre-crumbs" data-href="#station/reggae/dancehall"> / Dancehall</span>';
        public static $dub = '//*[@id="mCSB_20_container"]/ul/li[3]/a';
        public static $dubCrumbs = '<span class="sub-genre-crumbs" data-href="#station/reggae/dub"> / Dub</span>';
        public static $popReggae = '//*[@id="mCSB_20_container"]/ul/li[4]/a';
        public static $popReggaeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/reggae/pop-reggae"> / Pop Reggae</span>';
        public static $ragga = '//*[@id="mCSB_20_container"]/ul/li[5]/a';
        public static $raggaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/reggae/ragga"> / Ragga</span>';
        public static $reggaeRoots = '//*[@id="mCSB_20_container"]/ul/li[6]/a';
        public static $reggaeRootsCrumbs = '<span class="sub-genre-crumbs" data-href="#station/reggae/reggae-roots"> / Reggae Roots</span>';
        public static $rockSteady = '//*[@id="mCSB_20_container"]/ul/li[7]/a';
        public static $rockSteadyCrumbs = '<span class="sub-genre-crumbs" data-href="#station/reggae/rock-steady"> / Rock Steady</span>';


    public static $rockGenre = '#tab-21';
    public static $rockGenreCrumbs = '<a class="genre-crumbs" data-href="#station/rock" href="">Rock</a>';
        public static $adultAlbumAlternative = '//*[@id="mCSB_21_container"]/ul/li[1]/a';
        public static $adultAlbumAlternativeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/adult-album-alternative"> / Adult Album Alternative</span>';
        public static $britishInvasion = '//*[@id="mCSB_21_container"]/ul/li[2]/a';
        public static $britishInvasionCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/british-invasion"> / British Invasion</span>';
        public static $celticRock = '//*[@id="mCSB_21_container"]/ul/li[3]/a';
        public static $celticRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/celtic-rock"> / Celtic Rock</span>';
        public static $classicRock = '//*[@id="mCSB_21_container"]/ul/li[4]/a';
        public static $classicRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/classic-rock"> / Classic Rock</span>';
        public static $garageRock = '//*[@id="mCSB_21_container"]/ul/li[5]/a';
        public static $garageRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/garage-rock"> / Garage Rock</span>';
        public static $glam = '//*[@id="mCSB_21_container"]/ul/li[6]/a';
        public static $glamCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/glam"> / Glam</span>';
        public static $hardRock = '//*[@id="mCSB_21_container"]/ul/li[7]/a';
        public static $hardRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/hard-rock"> / Hard Rock</span>';
        public static $jamBands = '//*[@id="mCSB_21_container"]/ul/li[8]/a';
        public static $jamBandsCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/jam-bands"> / Jam Bands</span>';
        public static $jrock = '//*[@id="mCSB_21_container"]/ul/li[9]/a';
        public static $jrockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/jrock"> / JROCK</span>';
        public static $pianoRock = '//*[@id="mCSB_21_container"]/ul/li[10]/a';
        public static $pianoRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/piano-rock"> / Piano Rock</span>';
        public static $progRock = '//*[@id="mCSB_21_container"]/ul/li[11]/a';
        public static $progRockprogRockCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/prog-rock"> / Prog Rock</span>';
        public static $psyhodelic = '//*[@id="mCSB_21_container"]/ul/li[12]/a';
        public static $psyhodelicCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/psychedelic"> / Psychedelic</span>';
        public static $rockNroll = '//*[@id="mCSB_21_container"]/ul/li[13]/a';
        public static $rockNrollCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/rock-roll"> / Rock &amp; Roll</span>';
        public static $rockabilly = '//*[@id="mCSB_21_container"]/ul/li[14]/a';
        public static $rockabillyCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/rockabilly"> / Rockabilly</span>';
        public static $singerAndWriter = '//*[@id="mCSB_21_container"]/ul/li[15]/a';
        public static $singerAndWriterCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/singer-and-songwriter"> / Singer and Songwriter</span>';
        public static $surf = '//*[@id="mCSB_21_container"]/ul/li[16]/a';
        public static $surfCrumbs = '<span class="sub-genre-crumbs" data-href="#station/rock/surf"> / Surf</span>';


    public static $seasonalGenre = '#tab-22';
    public static $seasonalGenreCrumbs = '<a class="genre-crumbs" data-href="#station/seasonal-and-holiday" href="">Seasonal and Holiday</a>';
        public static $anniversary = '//*[@id="mCSB_22_container"]/ul/li[1]/a';
        public static $anniversaryCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/anniversary"> / Anniversary</span>';
        public static $birthday = '//*[@id="mCSB_22_container"]/ul/li[2]/a';
        public static $birthdayCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/birthday"> / Birthday</span>';
        public static $christmas = '//*[@id="mCSB_22_container"]/ul/li[3]/a';
        public static $christmasCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/christmas"> / Christmas</span>';
        public static $halloween = '//*[@id="mCSB_22_container"]/ul/li[4]/a';
        public static $halloweenCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/halloween"> / Halloween</span>';
        public static $hanukkah = '//*[@id="mCSB_22_container"]/ul/li[5]/a';
        public static $hanukkahCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/hanukkah"> / Hanukkah</span>';
        public static $honeymoon = '//*[@id="mCSB_22_container"]/ul/li[6]/a';
        public static $honeymoonCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/honeymoon"> / Honeymoon</span>';
        public static $kwanzaa = '//*[@id="mCSB_22_container"]/ul/li[7]/a';
        public static $kwanzaaCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/kwanzaa"> / Kwanzaa</span>';
        public static $valentine = '//*[@id="mCSB_22_container"]/ul/li[8]/a';
        public static $valentineCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/valentine"> / Valentine</span>';
        public static $wedding = '//*[@id="mCSB_22_container"]/ul/li[9]/a';
        public static $weddingCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/wedding"> / Wedding</span>';
        public static $winter = '//*[@id="mCSB_22_container"]/ul/li[10]/a';
        public static $winterCrumbs = '<span class="sub-genre-crumbs" data-href="#station/seasonal-and-holiday/winter"> / Winter</span>';



    public static $soundtracksGenre = '#tab-23';
    public static $soundtracksGenreCrumbs = '<a class="genre-crumbs" data-href="#station/soundtracks" href="">Soundtracks</a>';
    public static $anime = '//*[@id="mCSB_23_container"]/ul/li[1]/a';
    public static $animeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/soundtracks/anime"> / Anime</span>';
    public static $kids = '//*[@id="mCSB_23_container"]/ul/li[2]/a';
    public static $kidsCrumbs = '<span class="sub-genre-crumbs" data-href="#station/soundtracks/kids"> / Kids</span>';
    public static $originalScore = '//*[@id="mCSB_23_container"]/ul/li[3]/a';
    public static $originalScoreCrumbs = '<span class="sub-genre-crumbs" data-href="#station/soundtracks/original-score"> / Original Score</span>';
    public static $showtunes = '//*[@id="mCSB_23_container"]/ul/li[4]/a';
    public static $showtunesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/soundtracks/showtunes"> / Showtunes</span>';
    public static $videoGames = '//*[@id="mCSB_23_container"]/ul/li[5]/a';
    public static $videoGamesCrumbs = '<span class="sub-genre-crumbs" data-href="#station/soundtracks/video-game-music"> / Video Game Music</span>';



    public static $talkGenre = '#tab-24';
    public static $talkGenreCrumbs = '<a class="genre-crumbs" data-href="#station/talk" href="">Talk</a>';
        public static $blogTalk = '//*[@id="mCSB_24_container"]/ul/li[1]/a';
        public static $blogTalkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/blogtalk"> / BlogTalk</span>';
        public static $comedy = '//*[@id="mCSB_24_container"]/ul/li[2]/a';
        public static $comedyCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/comedy"> / Comedy</span>';
        public static $community = '//*[@id="mCSB_24_container"]/ul/li[3]/a';
        public static $communityCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/community"> / Community</span>';
        public static $educational = '//*[@id="mCSB_24_container"]/ul/li[4]/a';
        public static $educationalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/educational"> / Educational</span>';
        public static $government = '//*[@id="mCSB_24_container"]/ul/li[5]/a';
        public static $governmentCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/government"> / Government</span>';
        public static $news1 = '//*[@id="mCSB_24_container"]/ul/li[6]/a';
        public static $news1Crumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/news-1"> / News</span>';
        public static $oldTimeRadio = '//*[@id="mCSB_24_container"]/ul/li[7]/a';
        public static $oldTimeRadioCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/old-time-radio"> / Old Time Radio</span>';
        public static $otherTalk = '//*[@id="mCSB_24_container"]/ul/li[8]/a';
        public static $otherTalkCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/other-talk"> / Other Talk</span>';
        public static $political = '//*[@id="mCSB_24_container"]/ul/li[9]/a';
        public static $politicalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/political"> / Political</span>';
        public static $scanner = '//*[@id="mCSB_24_container"]/ul/li[10]/a';
        public static $scannerCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/scanner"> / Scanner</span>';
        public static $spokenWorld = '//*[@id="mCSB_24_container"]/ul/li[11]/a';
        public static $spokenWorldCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/spoken-word"> / Spoken Word</span>';
        public static $sport1 = '//*[@id="mCSB_24_container"]/ul/li[12]/a';
        public static $sport1Crumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/sports-1"> / Sports</span>';
        public static $technology = '//*[@id="mCSB_24_container"]/ul/li[13]/a';
        public static $technologyCrumbs = '<span class="sub-genre-crumbs" data-href="#station/talk/technology"> / Technology</span>';



    public static $themesGenre = '#tab-25';
    public static $themesGenreCrumbs = '<a class="genre-crumbs" data-href="#station/themes" href="">Themes</a>';
    public static $adult = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $adultCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/adult"> / Adult</span>';
    public static $bestOf = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $bestOfCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/best-of"> / Best Of</span>';
    public static $chill = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $chillCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/chill"> / Chill</span>';
    public static $eclectic = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $eclecticCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/eclectic"> / Eclectic</span>';
    public static $experimental = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $experimentalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/experimental"> / Experimental</span>';
    public static $female = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $femaleCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/female"> / Female</span>';
    public static $heartache = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $heartacheCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/heartache"> / Heartache</span>';
    public static $instrumental = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $instrumentalCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/instrumental"> / Instrumental</span>';
    public static $lgbt = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $lgbtCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/lgbt"> / LGBT</span>';
    public static $loveAndRomance = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $loveAndRomanceCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/love-and-romance"> / Love and Romance</span>';
    public static $partymix = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $partymixCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/party-mix"> / Party Mix</span>';
    public static $patriotic = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $patrioticCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/patriotic"> / Patriotic</span>';
    public static $rainyDatMix = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $rainyDatMixCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/rainy-day-mix"> / Rainy Day Mix</span>';
    public static $realty = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $realtyCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/reality"> / Reality</span>';
    public static $sexy = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $sexyCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/sexy"> / Sexy</span>';
    public static $shuffle = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $shuffleCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/shuffle"> / Shuffle</span>';
    public static $travelMix = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $travelMixCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/travel-mix"> / Travel Mix</span>';
    public static $tribute = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $tributeCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/tribute"> / Tribute</span>';
    public static $trippy = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $trippyCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/trippy"> / Trippy</span>';
    public static $workMix = '//*[@id="mCSB_25_container"]/ul/li[1]/a';
    public static $workMixCrumbs = '<span class="sub-genre-crumbs" data-href="#station/themes/work-mix"> / Work Mix</span>';

}
